"""initial_schema

Revision ID: bcf42b88479c
Revises: e3c76004be45
Create Date: 2024-11-29 18:18:53.466558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bcf42b88479c'
down_revision: Union[str, None] = 'e3c76004be45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'performance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'performance_logs', 'trading_crews', ['crew_id'], ['id'])
    op.drop_column('performance_logs', 'metrics')
    op.drop_column('performance_logs', 'win_rate')
    op.drop_column('performance_logs', 'pnl')
    op.drop_column('performance_logs', 'log_type')
    op.drop_column('performance_logs', 'max_drawdown')
    op.drop_column('performance_logs', 'sharpe_ratio')
    op.drop_column('performance_logs', 'trading_crew_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_logs', sa.Column('trading_crew_id', sa.INTEGER(), nullable=True))
    op.add_column('performance_logs', sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True))
    op.add_column('performance_logs', sa.Column('max_drawdown', sa.FLOAT(), nullable=True))
    op.add_column('performance_logs', sa.Column('log_type', sa.VARCHAR(), nullable=True))
    op.add_column('performance_logs', sa.Column('pnl', sa.FLOAT(), nullable=True))
    op.add_column('performance_logs', sa.Column('win_rate', sa.FLOAT(), nullable=True))
    op.add_column('performance_logs', sa.Column('metrics', sqlite.JSON(), nullable=True))
    op.drop_constraint(None, 'performance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'performance_logs', 'trading_crews', ['trading_crew_id'], ['id'])
    # ### end Alembic commands ###
