"""create_all_tables

Revision ID: e3c76004be45
Revises: a98c9f26b8e8
Create Date: 2024-11-29 18:18:15.367649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e3c76004be45'
down_revision: Union[str, None] = 'a98c9f26b8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_data_id', table_name='market_data')
    op.drop_table('market_data')
    op.add_column('performance_logs', sa.Column('crew_id', sa.Integer(), nullable=True))
    op.add_column('performance_logs', sa.Column('profit', sa.Float(), nullable=True))
    op.drop_constraint(None, 'performance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'performance_logs', 'trading_crews', ['crew_id'], ['id'])
    op.drop_column('performance_logs', 'pnl')
    op.drop_column('performance_logs', 'trading_crew_id')
    op.drop_column('performance_logs', 'win_rate')
    op.drop_column('performance_logs', 'sharpe_ratio')
    op.drop_column('performance_logs', 'metrics')
    op.drop_column('performance_logs', 'log_type')
    op.drop_column('performance_logs', 'max_drawdown')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('performance_logs', sa.Column('max_drawdown', sa.FLOAT(), nullable=True))
    op.add_column('performance_logs', sa.Column('log_type', sa.VARCHAR(), nullable=True))
    op.add_column('performance_logs', sa.Column('metrics', sqlite.JSON(), nullable=True))
    op.add_column('performance_logs', sa.Column('sharpe_ratio', sa.FLOAT(), nullable=True))
    op.add_column('performance_logs', sa.Column('win_rate', sa.FLOAT(), nullable=True))
    op.add_column('performance_logs', sa.Column('trading_crew_id', sa.INTEGER(), nullable=True))
    op.add_column('performance_logs', sa.Column('pnl', sa.FLOAT(), nullable=True))
    op.drop_constraint(None, 'performance_logs', type_='foreignkey')
    op.create_foreign_key(None, 'performance_logs', 'trading_crews', ['trading_crew_id'], ['id'])
    op.drop_column('performance_logs', 'profit')
    op.drop_column('performance_logs', 'crew_id')
    op.create_table('market_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('crew_id', sa.INTEGER(), nullable=False),
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('interval', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('open_price', sa.FLOAT(), nullable=False),
    sa.Column('high_price', sa.FLOAT(), nullable=False),
    sa.Column('low_price', sa.FLOAT(), nullable=False),
    sa.Column('close_price', sa.FLOAT(), nullable=False),
    sa.Column('volume', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('additional_data', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['crew_id'], ['trading_crews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_market_data_id', 'market_data', ['id'], unique=False)
    # ### end Alembic commands ###
